Bump msrv to 1.56
This allows removal of `std::convert::{TryFrom, TryInfo}` since they are
included in the `std::prelude`.

Notice that they will receive the following error if not using =>1.56:
```
> cargo +1.55.0-x86_64-unknown-linux-gnu b
error: failed to parse manifest at `/home/wcampbell/projects/wcampbell/code/teleport/Cargo.toml`

Caused by:
  feature `edition2021` is required

  The package requires the Cargo feature called `edition2021`, but that feature is not stabilized
  in this version of Cargo (1.55.0 (32da73ab1 2021-08-23)).

  Consider trying a newer version of Cargo (this may require the nightly release).
  See https://doc.rust-lang.org/nightly/cargo/reference/unstable.html#edition-2021 for more
  information about the status of this feature.
```

But the future is here!

Signed-off-by: wcampbell <wcampbell1995@gmail.com>